- name: instatll rabbitmq-server
  yum: name=rabbitmq-server state=present

# config rabbitmq
- name: copy hosts to remote host
  copy: src=hosts dest=/etc/hosts
- name: copy .erlang.cookie to remote host
  copy: src=.erlang.cookie dest=/var/lib/rabbitmq/.erlang.cookie mode=400 owner=rabbitmq group=rabbitmq

# config rabbitmq cluster
- name: start rabbitmq service
  service: name=rabbitmq-server state=started enabled=yes
- name: stop app
  shell: /usr/sbin/rabbitmqctl stop_app
- name: add to cluster rabbit@rabbitmq171
  shell: /usr/sbin/rabbitmqctl join_cluster {{ cluster_node }}
- name: start app
  shell: /usr/sbin/rabbitmqctl start_app

# enable rabbitmq_management
- name: enable rabbitmq_management
  shell: /usr/lib/rabbitmq/lib/rabbitmq_server-3.1.5/sbin/rabbitmq-plugins enable rabbitmq_management 
